apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 3
  selector:
  matchLabels:
  app: database
  template:
  metadata:
  labels:
    app: database
  spec:
    containers:
      - name: postgres
    image: postgres:13
    env:
      - name: POSTGRES_PASSWORD
        value: "password123"
      - name: PGDATA
    value: "/var/lib/postgresql/data/pgdata"
  volumeMounts:
  - name: data
  mountPath: /var/lib/postgresql/data
  volumes:
    - name: data
  emptyDir: {}